"""a=int(input("Enter a number"))
b=int(input("Enter b number"))
x=int(input("Enter x number"))
print("and",a&b)
print("or",a|b)
print("xor",a^b)
print("not",~a)
print("x leftshift:",x<<2)
print("x rightshift:",x>>2)"""

a=int(input("Enter the number:"))
binary=bin(a)
octal=oct(a)
hexa=hex(a)
print("Binary:",binary)
print("Octal:",octal)
print("Hexa:",hexa)
