from tkinter import *
window=Tk()
window.title("Sign up")
window.configure(background="pink")
window.geometry("600x480")
fNvar=StringVar()
lNvar=StringVar()
def showHWorld():
    print("Hello world")
    fNam=fNvar.get()
    lNam=lNvar.get()
    print("First Name:",fNam)
    print("Last Name:",lNam)
def signUp():
    fLbl=Label(window,text="First name",bg="green").grid(row=0,column=0)
    lLbl=Label(window,text="Second name").grid(row=1,column=0)
    fName=Entry(window,textvariable=fNvar)
    lName=Entry(window,textvariable=lNvar)
    fName.grid(row=0,column=1)
    lName.grid(row=1,column=1)
    fNvar.set("First Name")
    lNvar.set("Last Name")
    Button(window,text="submit",bg="red",fg="blue",command=showHWorld).grid(row=2,column=0)
    window.mainloop()
signUp()
